CXX=g++
CC=gcc

CXX_FLAGS=-O3
C_FLAGS=

INCLUDE_DIRS=
LIBRARY_DIRS=
LIBRARIES=-lglut -lfftw3

LINK_FLAGS=



stokes: stokes.o main.o
	$(CXX) $(CXX_FLAGS) stokes.o main.o -o stokes $(LINK_FLAGS) $(INCLUDE_DIRS) $(DEFINES) $(LIBRARY_DIRS) $(LIBRARIES)

main.o: main.cpp stokes.h
	$(CXX) $(CXX_FLAGS) -c main.cpp  $(LINK_FLAGS) $(INCLUDE_DIRS) $(DEFINES) 

stokes.o: stokes.cpp stokes.h
	$(CXX) -c $(CXX_FLAGS) $(INCLUDE_DIRS) $(DEFINES) stokes.cpp

.PHONY: clean
clean:
	rm -f *.o stokes
